* Meta
Goal is documentation for using build tool. Not individual actions, but more the process used to record a script and create a playable version.
* VuGen
After creating a recording there are the following possible goals:
** Use as basis for completely new script
bld init
bld set-prjtype vugen
bld saveas <newdir>
** In newly created dir
Make sure libs in other projects are up-to-date; no pending puts to repo needed. We want the latest repo versions in our new script dir.
gac -> add to git source control
bld init
bld set-prjtype vugen
Edit .bld/config-<machine> and set testruns dir.
Edit .bld/config.tcl and set ALM domain/project.
bld split-action
bld templates
bld rb-trans
bld domains
Edit domains.ini
bld domains (to comment out domains to be ignored)
bld param-domain <main-domain>
bld remove-comment
bld remove-empty-lines
bld get hashmap.c transaction.c
gac -> Put result of these automatic actions in git.
Check other libs, maybe marked as local-new, could be only whitespace.
bld test -> check for errors and inconsistencies
compile script
check domains - if more than one.
comment web_add_cookie - maybe don't generate, but extra doc can be useful.
check SSL version - maybe generated in script, may need TLS or TLS1.2

Also:
<param-check> more correlation needed?
** Modify existing script
Die oorspronkelijk van iemand anders is.
gac -> add to git source control
bld init
bld set-prjtype vugen
Edit .bld/config-<machine> and set testruns dir.
;; bld split-action -> lijkt gevaarlijk.
;; bld templates -> lijkt gevaarlijk.
bld get transaction.c 
bld get y_core.c dynatrace.c functions.c logger.c
bld get configfile.c
bld rb-trans
manual: char * transaction alleen eenmaal bovenin.
manual: in vuser_init: set_trans_prefix("<UC>");
manual: in vuser_init: define and read config file.
touch scripttest.config
touch <other config files>
bld add-file scripttest.config
bld add-file <other config files>
bld domains
Edit domains.ini
bld domains (to comment out domains to be ignored)
bld param-domain <main-domain>
;; bld remove-comment
;; bld remove-empty-lines
gac -> Put result of these automatic actions in git.
bld test -> check for errors and inconsistencies
** Manual actions 25-11-2016
bld get logger.c -> not automatically done correctly yet.
bld put configfile.c -> possibly some whitespace changes
bld put dynatrace.c -> same
bld put functions.c -> same
bld put vugen.h -> same
bld put *_functions.c -> same
bld put y_core.c -> same
** Add actions to existing script
** General notes
*** Don't wait to long with correlations
[2016-12-20 10:31:26] Script will differ from recordings more and more, so correlations will be more difficult. Eg snapshot numbers may change, some code might be integrated.
* org-mode configuration
#+STARTUP: indent
#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: logdone
#+COLUMNS: %38ITEM(Details) %TAGS(Context) %7TODO(To Do) %5Effort(Time){:} %6CLOCKSUM{Total}
#+PROPERTY: Effort_ALL 0 0:10 0:20 0:30 1:00 2:00 3:00 4:00 8:00
#+TAGS: { OFFICE(o) HOME(h) } COMPUTER(c) PROJECT(p) READING(r) 
#+TAGS: DVD(d) LUNCHTIME(l)
#+SEQ_TODO: TODO(t) STARTED(s) WAITING(w) APPT(a) | DONE(d) CANCELLED(c) DEFERRED(f)



